---
- name: Create Network Backup Play
  hosts: rtr1
  gather_facts: false
  tasks:
    - name: Create time stamp for backup
      ansible.builtin.set_fact:
        datetime: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M') }}"

    - name: Create Network Backup and Push to SCM
      ansible.builtin.include_role:
        name: network.backup.backup
      vars:
        operation: backup
        type: "{{ backup_type }}"
        data_store:
          scm:
            origin:
              url: "https://github.com/rohitthakur2590/network_automation_backups"
              token: "{{ GH_TOKEN }}"
              user:
                name: rohitthakur2590
                email: rohitthakur2590@outlook.com
          backup_file_name: "{{ datetime }}"
